pofolio/pofolio/blog/urls.py
from django.urls import path

# urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index,name='home'),
    path('login/', views.login_view, name='login'),
    path('pofolio/', views.pofolio_view, name='pofolio'),
    path('progress/', views.course_progress, name='progress'),
    path('registers/<int:course_id>/', views.register_course, name='register_course'),
    path('unregister-course/<int:course_id>/', views.unregister_course, name='unregister_course'),
    path('confirm/<int:course_id>/', views.course_delete_confirmation_view, name='confirm'),
    path('blogs/', views.blog_view, name='blogs'),
    path('blogpost/<int:topic_id>/', views.blogpost_detail_view, name='blogpost_detail'),
    path('register/', views.register, name='register'),
    path('courses/',views.course_view,name="courses"),
    path("courses/<int:course_id>/",views.courses_detail,name="course_detail"),
    path("mytopic/<int:topic_id>/",views.mytopic_detail,name="mytopic_detail"),
    path('logout/', views.logout_view, name='logout'),
    path("topic/",views.create_topic,name="topic"),
    path("entry/",views.create_blogpost,name="entry"),
    path("profilepic/",views.profilepic_view,name="profilepic"),
    path("profile/", views.profile_view, name="profile"),
    path("topics",views.all_topics,name="topics"),
    path('topics/<int:topic_id>/', views.topic_detail, name='topic_detail'),
     # Other URL patterns...
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)



app_name="blog"

pofolio/pofolio/pofolio/urls.py
from django.contrib import admin
from django.urls import path,include
import requests

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('blog.urls',namespace='blog')),

]

pofolio/pofolio/blog/models.py
from django_quill.fields import QuillField
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager,User
from django.db import models
from django.contrib.auth.models import User
from tinymce import models as tinymce_models
from django.conf import settings


class PersonManager(BaseUserManager):
    def create_user(self, username, password=None,**extra_fields):
        if not username:
            raise ValueError('The Username field must be set')

        user = self.model(username=username)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password,**extra_fields):
        user = self.create_user(username=username, password=password)
        user.is_superuser = True
        user.is_staff = True
        user.is_active =True
        user.save(using=self._db)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)
    
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
    
        return user
    


class Person(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=150, unique=True)
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    profile_pic = models.ImageField(upload_to='images', height_field=None, width_field=None,blank=True)
    enroll_courses = models.ManyToManyField('Courses', related_name='students', blank=True)
    objects = PersonManager()
    USERNAME_FIELD = 'username'
    is_staff = models.BooleanField(default=False)
    
    
   
    def __str__(self):
            return self.username
    
    

class Courses(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images', height_field=None, width_field=None, max_length=None,blank=True)
    discritption = models.CharField(max_length=100,default='') 
    date = models.DateTimeField(auto_now_add=True)
    registered_users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    def __str__(self):
        return self.name


class Topic(models.Model):
    course = models.ForeignKey(Courses,on_delete=models.CASCADE)
    text= models.CharField(max_length=100)
    content = tinymce_models.HTMLField(blank=False,null=False)
    image = models.ImageField(upload_to='images', height_field=None, width_field=None, max_length=None,null=False,blank=True)
    code = tinymce_models.HTMLField(blank=True,null=False)
    date_of_entry = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f' {self.text} created  on {self.date_of_entry}'



class BlogPost(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True)
    topic = models.CharField(max_length=100)
    post_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images', height_field=None, width_field=None, max_length=None,null=False,blank=True)
 
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    code = tinymce_models.HTMLField(blank=False)
    content = tinymce_models.HTMLField()

    def __str__(self):
        return f"{self.user}'s Post on {self.post_date} in {self.course}"



class Profile(models.Model):
     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True)
     image = models.ImageField(upload_to='images', height_field=None, width_field=None, max_length=None)
     
     def __str__(self):
         return (f'{self.user} image')
     
class UserTopicProgress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    date_accessed = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'topic')

pofolio/pofolio/blog/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Person,BlogPost,Topic,Profile
from tinymce.widgets import TinyMCE

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class RegistrationForm(UserCreationForm):
    class Meta:
        model = Person
        fields = ['firstname', 'username', 'password1', 'password2','lastname']


# forms.py

class BlogPostForm(forms.ModelForm):
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    class Meta:
        model = BlogPost
        fields = ['topic','course','content','code','image']
        widgets = {
            'content': TinyMCE(attrs={'cols': 50, 'rows': 30},
                               mce_attrs={'content_style': 'body { background-color: auto; color: white; }'})
        }

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text','content','image','code','course']
        
        
class Profileform(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['profile_pic']

pofolio/pofolio/blog/views.py
from django.shortcuts import render
from django.http import HttpRequest,request
# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, RegistrationForm,BlogPostForm,TopicForm
from .models import Topic,Courses,BlogPost,Person,Profile, UserTopicProgress
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import BlogPostForm, TopicForm
from django.urls import reverse
from .forms import RegistrationForm, LoginForm,Profileform
from django.db.models import Q
from django.contrib import messages
from django.utils import timezone





links = {'links':{
        'linkdin':'https://hu.linkedin.com/in/abdulah-mamadee-kenneh-399023175',
        'facebook':'https://www.facebook.com/kennehabdulah1',
        'youtube':'https://www.youtube.com/channel/UCA70y0lJeIK3MKBj5xiUyew',
        'whatsapp':'https://wa.me/36206257091',
        }
               
           
           
        
        }


def index(request):
    topics = Topic.objects.all()
    search_query = request.GET.get('search')
    if search_query:
        # Search for topics based on the search query

        search_results = Topic.objects.filter(
        Q(text__icontains=search_query.strip()) |
        Q(text__icontains=search_query.replace(" ", "")) |
        Q(text__icontains=search_query.lower()) |
        Q(text__icontains=search_query.upper()) |
        Q(text__icontains=search_query.title()) |
        Q(content__icontains=search_query.strip()) |
        Q(content__icontains=search_query.replace(" ", "")) |
        Q(content__icontains=search_query.lower()) |
        Q(content__icontains=search_query.upper()) |
        Q(content__icontains=search_query.title())|
        Q(course__name__icontains=search_query.strip()) |
        Q(course__name__icontains=search_query.replace(" ", "")) |
        Q(course__name__icontains=search_query.lower()) |
        Q(course__name__icontains=search_query.upper()) |
        Q(course__name__icontains=search_query.title())
    ).distinct()
    else:
        search_results = None
   # courses = get_object_or_404(Courses,pk=course_id)
    contex={"topics":topics,'search_results':search_results,'search_value': search_query}  
    return render(request,"blog/home.html",contex)


def base_view(request):
    global links
    return render(request, "blog/base.html",links)

def pofolio_view(request):
    global links
    return render(request, "blog/pofolio.html",links)
  
def blog_view(request):
    #The function return the list of topic for all the topic in the Topic model 
    # Query the BlogPost objects associated with the retrieved user
    topics = Topic.objects.order_by('date_of_entry')
    blog_posts = BlogPost.objects.order_by('post_date')
    return render(request, "blog/myblog.html",context={'posts':blog_posts,'topics':topics})
# views.py



def blog_detail_view(request):
    return render(request,"blog/myblog.html")



def course_view(request):
    return render(request,template_name="blog/courses.html")
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('blog:home')  # Redirect to the homepage after login
    else:
        form = LoginForm()
    return render(request, 'blog/login.html', {'form': form})





def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            firstname = form.cleaned_data.get('firstname')
            lastname = form.cleaned_data.get('lastname')
            # Creating a new Person instance and saving it to the database
            new_user = Person.objects.create_user(username=username, password=password, firstname=firstname, lastname=lastname)
            new_user.save()
            # Authenticating the new user and logging them in
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('blog:home')  # Redirect to your desired URL after successful registration
    else:
        form = RegistrationForm()
    return render(request, 'blog/register.html', {'form': form})




def logout_view(request):
    logout(request)
    return redirect( reverse('blog:home'))  # Redirect to the homepage after logout

@login_required(login_url="/login/")

def create_blogpost(request):
    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES)
        if form.is_valid():
            blog_post = form.save(commit=False)
            blog_post.user = request.user
            blog_post.save()
            return redirect('blog:home')  # Redirect after successful form submission
    else:
        form = BlogPostForm()
    return render(request, 'blog/create_blogpost.html', {'form': form})

@login_required(login_url="/login/")
def create_topic(request):
    if request.method == 'POST':
        form = TopicForm(request.POST, request.FILES)
        if form.is_valid():
            form.user = request.user
            form.save()
            return redirect('blog:home')  # Redirect after successful form submission
    else:
        form = TopicForm()
    return render(request, 'blog/create_topic.html', {'form': form})

@login_required(login_url="/login/")
def all_topics(request):
    topics = Topic.objects.all().order_by('-date_of_entry')
    requested_topic = request.GET.get('search')
    #topics = Topic.objects.order_by('date_of_entry')
    courses = Courses.objects.all()
    posts = BlogPost.objects.order_by('post_date')
    contex ={"topics":topics,'courses':courses,'posts':posts}
    return render(request, 'blog/all_topic.html', context=contex)

@login_required(login_url="/login/")
def topic_detail(request, topic_id):
    topics= Topic.objects.order_by('date_of_entry')
    topic = get_object_or_404(Topic, pk=topic_id)
    return render(request, 'blog/topic_detail.html', {'topic': topic,'topics':topics})


@login_required(login_url="/login/")

@login_required(login_url="/login/")
def mytopic_detail(request, topic_id):
    mytopic = get_object_or_404(Topic, pk=topic_id)
    
    
    # Track user's progress for this topic
    UserTopicProgress.objects.get_or_create(user=request.user, topic=mytopic, defaults={'date_accessed': timezone.now()})
    progress= UserTopicProgress.objects.all()
    context = {'mytopic': mytopic,'progress':progress}
    return render(request, 'blog/mytopic_detail.html', context=context)

@login_required(login_url="/login/")
def courses_detail(request,course_id):
    mycourse = get_object_or_404(Courses,pk=course_id)
    topics = Topic.objects.filter(course=mycourse).order_by('date_of_entry')
    
     # Retrieve the courses the user is registered for
    registered_courses = request.user.enroll_courses.all()
    
    # Dictionary to store course progress
    course_progress_dict = {}
    
    # Iterate through registered courses
    for course in registered_courses:
        # Retrieve topics related to the course
        topics = Topic.objects.filter(course=course).order_by('date_of_entry')
        
        # Retrieve the topics the user has accessed for this course
        user_topics = request.user.user_topic_progress.filter(topic__course=course)
        
        # Store course, related topics, and user's progress in the dictionary
        course_progress_dict[course] = {'topics': topics, 'user_topics': user_topics}
        
    contex={"course":mycourse,'topics':topics,'course_progress_dict': course_progress_dict}
        
    return render(request,template_name="blog/course_detail.html",context=contex)



def blogpost_detail_view(request, topic_id):
    # Retrieve the topic object based on the provided username
    topics = Topic.objects.order_by('date_of_entry')
    blogs = BlogPost.objects.order_by('post_date')
    # Query the BlogPost objects associated with the retrieved user
    blog_posts = get_object_or_404(BlogPost, pk=topic_id)
    context = {'post': blog_posts,'topics':topics,'blogs':blogs}
    return render(request, template_name='blog/blogpost_detail.html', context=context)



# Registering user for course

# views.py
@login_required(login_url="/login/")
def register_course(request, course_id):
    course = get_object_or_404(Courses, pk=course_id)
    
    # Check if the user is already registered for the course
    if request.user in course.registered_users.all():
        messages.warning(request, 'You are already registered for this course.')
        return redirect('blog:profile')
    
    if request.method == 'POST':
        course.registered_users.add(request.user)
        messages.success(request, 'You have successfully registered for the course.')
        return redirect('blog:profile')
    
    return render(request, 'blog/register_course.html', {'course': course})




@login_required(login_url="/login/")
def profile_view(request):
    
    # Get the currently logged-in user
    mycourses = Courses.objects.filter(registered_users=request.user)
    #handling the profile form 
    if request.method == 'POST':
        form = Profileform(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('blog:profile')
    else:
        form = Profileform(instance=request.user)

    context={'mycourses':mycourses,'form':form}
    return render(request,template_name='blog/profile.html',context=context)


# the profileform view                 

pofolio/pofolio/blog/templates/blog/all_topic.html
{% extends 'blog/base.html' %}

{% load static %}
{% block content %}


<ul class='card-list-cont' style='display:flex;width:100vw; height:auto;flex-wrap: wrap; justify-content:center'>
   
    {% for course in courses %}




<li>
<div class="card-container container mt-5" >
    <div class="card-items">
        <h1 style='margin:20px'><a href="{% url 'blog:course_detail' course.id %}" >{{course}}</a></h1>
        <img src="{{ course.image.url }}" alt="{{course}}" class="card-image" style='margin:1rem;' >

         <p>
         {{course.discritption}}

        </p>
        <a class='button' href="{% url 'blog:register_course' course.id %}">Register</a>
     </div>
    </div>
</li>


{% endfor %}
</ul>



    </div>
{% endblock %}

pofolio/pofolio/blog/templates/blog/course_detail.html
{% extends 'blog/base.html' %}

{% block content %}

{% for p in  course_progress_dict %}

{{p}}
{{user_topics}}
{% endfor %}
<div class="blodg-continue container">
    <div class='row'>
<div class="blog-left-side col col-sm-12 col-xs-12 col-md-4 mb-5">
   <div class="topic-cont">
   
    
    <h2> Table of Contents </h2>
    {{mycourse}} 
       {% for mytopic in topics %}
    <li>
        
        <a href="{% url 'blog:mytopic_detail' mytopic.id %}">{{mytopic.text}}</a></li>
        {% endfor %}
   </div>
        </div>


        <div class="blog-main col col-sm-12 col-md-8 col-xs-12 col-12">
            {% for mytopic in topics %}
            <div class="post-head-continue2">
                <h1>{{mytopic.course}}</h1>
                <h3 style='text-align:center;text-decoration:underline;color:#007aff'>{{mytopic.text}}</h3>
                <div>
            
                    <p class="date">{{user.username}}, posted on {{mytopic.date_of_entry|date:'M d, Y H:i'}}</p>
                </div>

            </div>
            <hr>
            {% if  mytopic.content == "True" %}

            {% else %}

             <div class="paragraph">
                <p>{{mytopic.content|safe}}</p>
                </div>



             {% endif %}

             {% if mytopic.code %}
             <pre>
                 <code class="python" id="code-block">
             {{mytopic.code|safe}}
             </code>
             </pre>
             {% endif %}

            

             {% if mytopic.image == 'True' %}
             {% elif not mytopic.image %}
             {% else %}
             <div class='code-image'>             
                <img src="{{ mytopic.image.url }}">
             </div>
             {% endif %}
             {% endfor %}
  </div>

    </div>
</div>


{% endblock %}

pofolio/pofolio/blog/templates/blog/courses.html
{% extends 'blog/base.html' %}

pofolio/pofolio/blog/templates/blog/courses_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<h1> This is the course detail view </h1>

{% endblock %}

pofolio/pofolio/blog/templates/blog/create_blogpost.html
{% extends 'blog/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container-fluid justify-content-center  d-flex  " >
    <form  class='col col-8 outline-light bg-light justify-content-center  w-80 mx-auto mt-5' action='{% url 'blog:entry' %}' method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class='row m-5'>
        <h2 class="form-heading">Create blog post</h2>
      <div class="mb-3">
        <label  class="form-label">topic</label>
        {% render_field form.topic class="form-control form-control-lg"   placeholder=" Title of post "  aria-label=".form-control-lg example"%}
       
      </div>

      <div class="mb-3">
        <label for="disabledSelect" class="form-label">course</label>
        {% render_field form.course class="form-control form-control-lg"   placeholder=" Enter course "  aria-label=".form-control-lg example"%}
        
        
      </div>
      
      <div class="mb-3">
        <label for="disabledSelect" class="form-label">code</label>
        {% render_field form.code class="form-control form-control-lg"   placeholder=" Enter code "  aria-label=".form-control-lg example"%}
        
        
      </div>
      
      <div class="mb-3">
        <label for="disabledSelect" class="form-label">content</label>
        {% render_field form.content class="form-control form-control-lg"   placeholder=" Enter post content "  aria-label=".form-control-lg example"%}
        
        
      </div>
      <div class="mb-3">
        <label for="disabledSelect" class="form-label">image</label>
        {% render_field form.image class="form-control form-control-lg"   placeholder=" Enter post content "  aria-label=".form-control-lg example"%}
        
        
      </div>
      <button type="submit" class="btn btn-primary mb-5">Submit</button>
    </fieldset>
  </form>
</div>
{% endblock %}

pofolio/pofolio/blog/templates/blog/myblog.html
{% extends 'blog/base.html' %}

{% block content %}


<div class="continue">
    <div class='row bg-none'>
   <div class="blog-left-side col col-md-3 col-sm-12 mb-3 ">
   <div class="topic-cont ">
    <h2> Table of Contents</h2>

       {% for topic in topics %}   
       <li>
        <a href="{% url 'blog:topic_detail' topic.id %}">{{topic.text}}</a></li>
       {% endfor %}

   </div>
        </div>

        <div class=" col col-sm-12 col-md-6 blog-main">
            {% if posts %}
          {% for post in posts %}
         
            <div class="post-head-continue2">

                <h1>{{post.topic}}</h1>
                <div>
                    <img  src="{{ post.user.profile_pic.url }}" alt="Profile Picture" class="profile-pictur" style="width: 50px; height:50px ;border-radius:50%" >
    
                    <p class="date">{{post.user}}, posted on {{post.post_date|date:'M d, Y H:i'}}</p>
                </div>

            </div>
            <hr>
             <div class="paragraph">
             <p>{{post.content|safe}}</p>
             </div>
            {% if post.code %}
            <pre>
                <code class="python" id="code-block">
            {{post.code|safe}}
            </code>
            </pre>
            {% endif %}

            
   {% endfor %}

            {% else %}
            <h2> Coming soon! </h2>
            {% endif %}
        </div>


        <div class=" col col-xl-3 col-md-3 col-sm-12 blog-right-side fixed-right">
            <div class="topic-cont">
                
          
          <h2> Recent Posts </h2>
           {% for post in posts%}
                <li><a href="{% url 'blog:blogpost_detail' post.id %}">{{post.topic}}</a></li>
                {% endfor %}
                <a class='button' href="{% url 'blog:entry' %}" style='margin-top:30px !important'>Create New post</a>

            </div>
        </div>
    </div>


{% endblock %}

pofolio/pofolio/blog/templates/blog/profile.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5 w-60 "  >
    <div class="row justify-content-center col-12"  >
        <div class="col-md-8">
            <div class="card" style="width: 100%;">
                <div class="card-header">
                    <h1 class="mb-0">Profile</h1>
                </div>
                <div class="card-body text-center"  >
                    {% if request.user.profile_pic %}
                        <img  src="{{ request.user.profile_pic.url }}" alt="Profile Picture" class="profile-picture" style="width: 100px; height:100px " >
                    
                    {% else %}
                        <p class="text-muted">No profile picture available.</p>
                    {% endif %}
                    <p class="mt-3">Username: {{ request.user.username }}</p>
                    <p>First Name: {{ request.user.firstname }}</p>
                    <p>Last Name: {{ request.user.lastname }}</p>
                    <h3>Upload Profile Picture</h3>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit"  class='btn btn-success'>Upload</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>

<hr style='background:white;height:25px'>
{% if mycourses %}
<h1 class="profile-heading">Registered courses </h1>
{% else %}
<h1 class="profile-heading"> You have not Registered for any course yet </h1>
<p style='color:white'>Take a look at these courses: <a class='button' href="{% url 'blog:topics' %}">click me</a></p>
{% endif %}
<ul class='card-list-cont container' style='display:flex;width:100vw; height:auto;flex-wrap: wrap; justify-content:center'>

    {% for course in mycourses %}
<li >

<div class="card-container" >
    <div class="card-items">
        <h1 style='margin:20px'><a href="{% url 'blog:course_detail' course.id %}" >{{course}}</a></h1>
        <img src="{{ course.image.url }}" alt="{{course}}" class="card-image" style='margin:1rem;' >

         <p>
         {{course.discritption}}

        </p>
        <a class='button' href="{% url 'blog:course_detail' course.id %}">Read Me</a>
        <a class='button' href="{% url 'blog:confirm' course.id %}" style='float:right'>Unregister</a>
     </div>
    </div></li>



{% endfor %}
</ul>


{% comment %} !-- <div class="card-container">
    <div class="card-items">
         <h2>Python</h2>
         <img src="{% static 'blog/images/download.jpeg' %}" alt="Python" class="card-image"  >

         <p> Are you ready to master Python? Learn the most versatile and powerful programming language that serves as a foundation for various applications.

         <button>Read Me</button></p>
     </div>
   <div class="card-items">
        <h2>Matplotlib</h2>
        <img src="{% static 'blog/images/mat.png' %}" alt="Matplotlib" class="card-image"  >
        <p>Enhance your data visualization skills with Matplotlib. Create visually stunning and informative plots and graphs to effectively communicate your data.
        <button>Read Me</button></p>

    </div>
 
    <div class="card-items">
           <h2>Pandas</h2>

           <img src="{% static 'blog/images/pandas_logo.png' %}" alt="Pandas" class="card-image"  >
           <p>  Discover the power of Pandas, a Python library essential for efficient data manipulation and analysis. Unlock the potential of large datasets and maximize your data processing capabilities.
          <button>Read Me</button></p>
    </div>
</div>
</div> --> {% endcomment %}








{% endblock %}

pofolio/pofolio/blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container ">
    <div class="row">
        <div class="col-md-6 offset-md-3 bg-light  mt-5">
            <h3 class="form-heading">Register</h3>
            <form method="post">
                {% csrf_token %}
                {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                        <strong>Error:</strong> Please correct the following errors.
                        <ul>
                            {% for field, error_list in form.errors.items %}
                                {% for error in error_list %}
                                    <li>{{ field|title }}: {{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_firstname">First Name</label>
                    {{ form.firstname|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="id_lastname">Last Name</label>
                    {{ form.lastname|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="id_username">Username</label>
                    {{ form.username|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="id_password1">Password</label>
                    {{ form.password1|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="id_password2">Confirm Password</label>
                    {{ form.password2|add_class:"form-control" }}
                </div>
               
                <button type="submit" class="btn btn-primary mb-5">Register</button>
            </form>
        </div>
    </div>
</div>


    
{% endblock %}

pofolio/pofolio/blog/templates/blog/topic_detail.html
{% extends 'blog/base.html' %}

{% block content %}


<div class="blog-coxntinue container ">
    <div class='row'>
        <div class="blog-left-side col col-sm-12 col-xs-12 col-md-4 mb-5">
            <div class="topic-cont">
                <h2> Table of Contents</h2>
                {% for mytopic in topics %}
                <li>
                    <a href="{% url 'blog:topic_detail' mytopic.id %}">{{mytopic.text}}</a></li>
                {% endfor %} 
            </div>
        </div>

                <div class="blog-main col col-sm-12 col-md-8 col-xs-12 col-12">
                    <div class="post-head-continue2">

                        <h1>{{topic.course}}</h1>
                        <div>
                           <p class="date">{{user.username}}, posted on {{topic.date_of_entry|date:'M d, Y H:i'}}</p>
                        </div>

                    </div>
                    <hr>
                    {% if topic.content == 'True' %}
                    {% else %}           
                    
                        <div class="paragraph">
                            <p>{{topic.content|safe}}</p>
                        </div>
                    
                    {% endif %}


                    {% if mytopic.code %}
                    <pre>
                        <code class="python" id="code-block">
                    {{topic.code|safe}}
                    </code>
                    </pre>
                    {% endif %}

                    {% if topic.image == 'True' %}

                    {% elif not topic.image %}
                    {% else %}
                    <div class='code-image'>             
                        <img src="{{ topic.image.url }}">
                    </div>
                    {% endif %}



                </div>
    </div>

</div>

    {% endblock %}